# -*- coding: utf-8 -*-
"""
/***************************************************************************
 aceo
                                 A QGIS plugin
 GUI tools for AgriCarbon-EO processing chain
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-05-25
        copyright            : (C) 2021 by CESBIO
        email                : ludox09@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load aceo class from file aceo.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .aceo_plugin import aceo
    return aceo(iface)
